version: 0.0
os: windows
files:
  - source: \dist\purchasing.war
    destination: C:\Tomcat\apache-tomcat-9.0.0.M1\webapps
hooks:
  BeforeInstall:
    - location: \deploy\before-install.bat
      timeout: 900
  AfterInstall:
    - location: \deploy\after-install.bat
      timeout: 900
